import type { CsExpr, CsProgram, CsStatement } from '../../ir/csharp.js';
const ident = (s: string): string => {
  if (!/^(?:a|b|F)\d+$/.test(s)) throw new Error(`Invalid generated identifier ${s}`);
  return s;
};
function quote(value: string): string {
  let s = '"';
  for (let i = 0; i < value.length; i++) {
    const c = value.charCodeAt(i);
    s += c < 32 || c > 126 ? `\\u${c.toString(16).padStart(4, '0')}` : c === 34 ? '\\"' : c === 92 ? '\\\\' : value[i];
  }
  return s + '"';
}
function number(value: number): string {
  if (Number.isNaN(value)) return 'double.NaN';
  if (!Number.isFinite(value)) return value < 0 ? 'double.NegativeInfinity' : 'double.PositiveInfinity';
  if (Object.is(value, -0)) return '-0.0d';
  return `${value}d`;
}
const calls = new Set(['JsValue.IsTruthy', 'JsOperators.Add', 'JsOperators.StrictEquals', 'JsOperators.LooseEquals',
  'JsOperators.LessThan', 'JsOperators.LessThanOrEqual', 'JsOperators.GreaterThan', 'JsOperators.GreaterThanOrEqual',
  'JsCoercion.ToNumberPrimitive', 'JsCoercion.ToInt32Primitive', 'JsGlobals.IsFinitePrimitive', 'JsGlobals.IsNaNPrimitive',
  'JsGlobals.ParseFloatPrimitive', 'JsGlobals.ParseIntPrimitive', 'JsNumber.ParseFloatPrimitive', 'JsNumber.ParseIntPrimitive',
  'double.IsFinite', 'double.IsNaN', 'JsReference.Assign',
  'JsReference.AddAssign', 'JsReference.SubtractAssignNumber', 'JsReference.MultiplyAssignNumber',
  'JsReference.DivideAssignNumber', 'JsReference.RemainderAssignNumber', 'JsReference.PrefixIncrementNumber',
  'JsReference.PostfixIncrementNumber', 'JsReference.PrefixDecrementNumber', 'JsReference.PostfixDecrementNumber',
  'JsConsole.Log', 'string.Concat', 'JsObject.Create', 'JsObject.DefineDataProperty', 'JsObject.GetProperty',
  'JsObject.SetProperty', 'JsObject.HasOwn', 'JsArray.Create', 'JsArray.DefineElement', 'JsArray.Length', 'JsArray.Push',
  'JsMicrotaskQueue.Enqueue', 'JsMicrotaskQueue.Drain']);
function expr(e: CsExpr): string {
  switch (e.kind) {
    case 'literal': return e.repr === 'number' ? number(e.value) : e.repr === 'string' ? quote(e.value) : String(e.value);
    case 'read': return ident(e.name);
    case 'ref': return `ref ${ident(e.name)}`;
    case 'functionRef': return ident(e.name);
    case 'member': return e.name;
    case 'call':
      if (!calls.has(e.target)) ident(e.target);
      return `${e.target}(${e.args.map(expr).join(', ')})`;
    case 'box': {
      const method = { number: 'FromNumber', string: 'FromString', boolean: 'FromBoolean' }[e.value.repr as 'number' | 'string' | 'boolean'];
      if (!method) throw new Error('Invalid boxing IR');
      return `JsValue.${method}(${expr(e.value)})`;
    }
    case 'unbox': return `(${expr(e.value)}).${{ number: 'Number', string: 'String', boolean: 'Boolean' }[e.repr]}`;
    case 'binary':
      if (!['+', '-', '*', '/', '%', '<', '<=', '>', '>=', '=='].includes(e.op)) throw new Error('Invalid binary IR');
      return `(${expr(e.left)} ${e.op} ${expr(e.right)})`;
    case 'unary': return `(${e.op}${expr(e.value)})`;
  }
}
export function emitCSharp(program: CsProgram): string {
  const lines = ['// Generated by j2cs-compiler. See compilation.json for rule proofs.', 'using J2cs.Runtime;', '', 'internal static class Program', '{'];
  type EmitMode = 'normal' | 'asyncFunction' | 'asyncCallback';
  function line(depth: number, s: string): void { lines.push('    '.repeat(depth) + s); }
  function body(statements: CsStatement[], depth: number, mode: EmitMode = 'normal'): void {
    statements.forEach(s => statement(s, depth, mode));
  }
  function block(s: CsStatement, d: number, mode: EmitMode = 'normal'): void {
    line(d, '{'); body(s.kind === 'block' ? s.body : [s], d + 1, mode); line(d, '}');
  }
  function statement(s: CsStatement, d: number, mode: EmitMode = 'normal'): void {
    switch (s.kind) {
      case 'variable': line(d, `JsValue ${ident(s.name)} = ${expr(s.initializer)};`); return;
      case 'expression': line(d, `_ = ${expr(s.expression)};`); return;
      case 'return': line(d, `return ${expr(s.value)};`); return;
      case 'asyncReturn':
        if (mode === 'normal') throw new Error('asyncReturn outside async emission mode');
        line(d, `_ = ${expr(s.value)};`);
        line(d, mode === 'asyncFunction' ? 'return JsUndefined.Value;' : 'return;');
        return;
      case 'awaitValue':
        if (mode === 'normal') throw new Error('awaitValue outside async emission mode');
        line(d, `JsAsync.AwaitValue(${expr(s.value)}, ${ident(s.parameter)} =>`);
        line(d, '{');
        if (s.binding) line(d + 1, `JsValue ${ident(s.binding)} = ${ident(s.parameter)};`);
        body(s.continuation, d + 1, 'asyncCallback');
        line(d, '});');
        line(d, mode === 'asyncFunction' ? 'return JsUndefined.Value;' : 'return;');
        return;
      case 'break': line(d, 'break;'); return;
      case 'continue': line(d, 'continue;'); return;
      case 'block': block(s, d, mode); return;
      case 'if':
        line(d, `if (${expr(s.condition)})`); block(s.then, d, mode);
        if (s.otherwise) { line(d, 'else'); block(s.otherwise, d, mode); } return;
      case 'while': line(d, `while (${expr(s.condition)})`); block(s.body, d, mode); return;
      case 'doWhile': line(d, 'do'); block(s.body, d, mode); line(d, `while (${expr(s.condition)});`); return;
      case 'for':
        line(d, `for (; ${s.condition ? expr(s.condition) : ''}; ${s.update ? `_ = ${expr(s.update)}` : ''})`);
        block(s.body, d, mode); return;
    }
  }
  line(1, 'private static void Main()'); line(1, '{'); body(program.body, 2); line(1, '}');
  for (const fn of program.functions) {
    line(0, ''); line(1, `private static JsValue ${ident(fn.name)}(${fn.params.map(p => `JsValue ${ident(p)}`).join(', ')})`);
    line(1, '{'); body(fn.body, 2, fn.asyncMicrotask ? 'asyncFunction' : 'normal'); line(1, '}');
  }
  lines.push('}', ''); return lines.join('\n');
}
