import type { CsExpr, CsProgram, CsStatement } from '../../ir/csharp.js';
const ident = (s: string): string => {
  if (!/^(?:b|F)\d+$/.test(s)) throw new Error(`Invalid generated identifier ${s}`);
  return s;
};
function quote(value: string): string {
  let s = '"';
  for (let i = 0; i < value.length; i++) {
    const c = value.charCodeAt(i);
    s += c < 32 || c > 126 ? `\\u${c.toString(16).padStart(4, '0')}` : c === 34 ? '\\"' : c === 92 ? '\\\\' : value[i];
  }
  return s + '"';
}
function number(value: number): string {
  if (Number.isNaN(value)) return 'double.NaN';
  if (!Number.isFinite(value)) return value < 0 ? 'double.NegativeInfinity' : 'double.PositiveInfinity';
  if (Object.is(value, -0)) return '-0.0d';
  return `${value}d`;
}
const calls = new Set(['JsValue.IsTruthy', 'JsOperators.Add', 'JsOperators.StrictEquals', 'JsOperators.LooseEquals',
  'JsOperators.LessThan', 'JsOperators.LessThanOrEqual', 'JsOperators.GreaterThan', 'JsOperators.GreaterThanOrEqual',
  'JsCoercion.ToNumberPrimitive', 'JsCoercion.ToInt32Primitive', 'JsGlobals.IsFinitePrimitive', 'JsGlobals.IsNaNPrimitive',
  'JsGlobals.ParseFloatPrimitive', 'JsGlobals.ParseIntPrimitive', 'JsNumber.ParseFloatPrimitive', 'JsNumber.ParseIntPrimitive',
  'double.IsFinite', 'double.IsNaN', 'JsReference.Assign',
  'JsReference.AddAssign', 'JsReference.SubtractAssignNumber', 'JsReference.MultiplyAssignNumber',
  'JsReference.DivideAssignNumber', 'JsReference.RemainderAssignNumber', 'JsReference.PrefixIncrementNumber',
  'JsReference.PostfixIncrementNumber', 'JsReference.PrefixDecrementNumber', 'JsReference.PostfixDecrementNumber',
  'JsConsole.Log', 'JsCompletion.Return', 'JsCompletion.Break', 'JsCompletion.Continue', 'JsException.Wrap',
  'string.Concat', 'JsObject.Create', 'JsObject.DefineDataProperty', 'JsObject.GetProperty',
  'JsObject.SetProperty', 'JsObject.HasOwn', 'JsArray.Create', 'JsArray.DefineElement', 'JsArray.Length', 'JsArray.Push']);
function expr(e: CsExpr): string {
  switch (e.kind) {
    case 'literal': return e.repr === 'number' ? number(e.value) : e.repr === 'string' ? quote(e.value) : String(e.value);
    case 'read': return ident(e.name);
    case 'ref': return `ref ${ident(e.name)}`;
    case 'member': return e.name;
    case 'call':
      if (!calls.has(e.target)) ident(e.target);
      return `${e.target}(${e.args.map(expr).join(', ')})`;
    case 'box': {
      const method = { number: 'FromNumber', string: 'FromString', boolean: 'FromBoolean' }[e.value.repr as 'number' | 'string' | 'boolean'];
      if (!method) throw new Error('Invalid boxing IR');
      return `JsValue.${method}(${expr(e.value)})`;
    }
    case 'unbox': return `(${expr(e.value)}).${{ number: 'Number', string: 'String', boolean: 'Boolean' }[e.repr]}`;
    case 'binary':
      if (!['+', '-', '*', '/', '%', '<', '<=', '>', '>=', '=='].includes(e.op)) throw new Error('Invalid binary IR');
      return `(${expr(e.left)} ${e.op} ${expr(e.right)})`;
    case 'unary': return `(${e.op}${expr(e.value)})`;
  }
}
export function emitCSharp(program: CsProgram): string {
  const lines = ['// Generated by j2cs-compiler. See compilation.json for rule proofs.', 'using J2cs.Runtime;', '', 'internal static class Program', '{'];
  let temporary = 0;
  const temp = (kind: string): string => `__j2cs_${kind}${temporary++}`;
  function line(depth: number, s: string): void { lines.push('    '.repeat(depth) + s); }
  function body(statements: CsStatement[], depth: number): void { statements.forEach(s => statement(s, depth)); }
  function block(s: CsStatement, d: number): void { line(d, '{'); body(s.kind === 'block' ? s.body : [s], d + 1); line(d, '}'); }
  function loopBlock(s: CsStatement, d: number): void {
    const completion = temp('loop');
    line(d, '{');
    line(d + 1, 'try'); block(s, d + 1);
    line(d + 1, `catch (JsCompletionSignal ${completion}) when (${completion}.Kind == JsCompletionKind.Continue)`);
    line(d + 1, '{'); line(d + 2, 'continue;'); line(d + 1, '}');
    line(d + 1, `catch (JsCompletionSignal ${completion}) when (${completion}.Kind == JsCompletionKind.Break)`);
    line(d + 1, '{'); line(d + 2, 'break;'); line(d + 1, '}');
    line(d, '}');
  }
  function statement(s: CsStatement, d: number): void {
    switch (s.kind) {
      case 'variable': line(d, `JsValue ${ident(s.name)} = ${expr(s.initializer)};`); return;
      case 'expression': line(d, `_ = ${expr(s.expression)};`); return;
      case 'return': line(d, `return ${expr(s.value)};`); return;
      case 'break': line(d, 'break;'); return;
      case 'continue': line(d, 'continue;'); return;
      case 'throw': line(d, `throw ${expr(s.value)};`); return;
      case 'try': {
        line(d, 'try'); block(s.body, d);
        if (s.catchClause) {
          const exception = temp('exception');
          line(d, `catch (JsException ${exception})`);
          line(d, '{');
          if (s.catchClause.binding)
            line(d + 1, `JsValue ${ident(s.catchClause.binding)} = JsException.Unwrap(${exception});`);
          body(s.catchClause.body.kind === 'block' ? s.catchClause.body.body : [s.catchClause.body], d + 1);
          line(d, '}');
        }
        if (s.finallyBlock) { line(d, 'finally'); block(s.finallyBlock, d); }
        return;
      }
      case 'block': block(s, d); return;
      case 'if':
        line(d, `if (${expr(s.condition)})`); block(s.then, d);
        if (s.otherwise) { line(d, 'else'); block(s.otherwise, d); } return;
      case 'while': line(d, `while (${expr(s.condition)})`); loopBlock(s.body, d); return;
      case 'doWhile': line(d, 'do'); loopBlock(s.body, d); line(d, `while (${expr(s.condition)});`); return;
      case 'for':
        line(d, `for (; ${s.condition ? expr(s.condition) : ''}; ${s.update ? `_ = ${expr(s.update)}` : ''})`);
        loopBlock(s.body, d); return;
    }
  }
  line(1, 'private static void Main()'); line(1, '{'); body(program.body, 2); line(1, '}');
  for (const fn of program.functions) {
    const completion = temp('function');
    line(0, ''); line(1, `private static JsValue ${ident(fn.name)}(${fn.params.map(p => `JsValue ${ident(p)}`).join(', ')})`);
    line(1, '{');
    line(2, 'try'); line(2, '{'); body(fn.body, 3); line(2, '}');
    line(2, `catch (JsCompletionSignal ${completion}) when (${completion}.Kind == JsCompletionKind.Return)`);
    line(2, '{'); line(3, `return ${completion}.Value;`); line(2, '}');
    line(2, 'throw new System.InvalidOperationException("JavaScript function completed without a Return completion.");');
    line(1, '}');
  }
  lines.push('}', ''); return lines.join('\n');
}
