import { fail } from '../diagnostics/index.js';
import type { CsProgram } from '../ir/csharp.js';
import type { RuleIndex } from '../rules/index.js';
import type { ClassExpr, ParsedClass, ParsedClassProgram, ParsedStaticMethod } from '../parser/classes.js';
import { analyzeClassProgram } from './class.js';

const quote = (value: string): string => {
  let result = '"';
  for (let i = 0; i < value.length; i++) {
    const c = value.charCodeAt(i);
    result += c < 32 || c > 126 ? `\\u${c.toString(16).padStart(4, '0')}`
      : c === 34 ? '\\"' : c === 92 ? '\\\\' : value[i];
  }
  return result + '"';
};
const number = (value: number): string => {
  if (Number.isNaN(value)) return 'double.NaN';
  if (!Number.isFinite(value)) return value < 0 ? 'double.NegativeInfinity' : 'double.PositiveInfinity';
  if (Object.is(value, -0)) return '-0.0d';
  return `${value}d`;
};

export function compileClassProgram(program: ParsedClassProgram, index: RuleIndex) {
  const plan = analyzeClassProgram(program, index.database);
  if (plan.deferred.length) {
    const first = plan.deferred[0]!;
    fail('E_CLASS_DEPENDENCY',
      `${first.feature} requires unmerged semantic infrastructure: ${first.dependency}. The class lane remains fail-closed.`,
      first.span, { canonicalRules: first.canonicalRules, allDeferred: plan.deferred });
  }

  const classes = new Map<string, { parsed: ParsedClass; name: string; ordinal: number }>();
  program.classes.forEach((parsed, ordinal) => classes.set(parsed.bindingName, { parsed, name: `C${ordinal}`, ordinal }));
  const methodNames = new Map<ParsedStaticMethod, string>();
  for (const { parsed, ordinal } of classes.values()) {
    let methodOrdinal = 0;
    for (const element of parsed.elements)
      if (element.kind === 'staticMethod') methodNames.set(element, `M${ordinal}_${methodOrdinal++}`);
  }

  const classRef = (name: string, exprSpan: ClassExpr['span']): string =>
    classes.get(name)?.name ?? fail('E_CLASS_UNRESOLVED', `Unresolved class binding '${name}'.`, exprSpan);

  function emitExpr(expr: ClassExpr): string {
    switch (expr.kind) {
      case 'literal':
        if (expr.value === undefined) return 'JsUndefined.Value';
        if (expr.value === null) return 'JsNull.Value';
        if (typeof expr.value === 'number') return `JsValue.FromNumber(${number(expr.value)})`;
        if (typeof expr.value === 'string') return `JsValue.FromString(${quote(expr.value)})`;
        return `JsValue.FromBoolean(${expr.value ? 'true' : 'false'})`;
      case 'staticRead':
        plan.resolveField(expr.className, expr.property, expr.span);
        return `JsClass.GetStatic(${classRef(expr.className, expr.span)}, ${quote(expr.property)})`;
      case 'staticCall': {
        if (expr.args.length) fail('E_CLASS_ARITY_DEPENDENCY', 'Static class calls with arguments remain fail-closed.', expr.span);
        const resolved = plan.resolveMethod(expr.className, expr.method, expr.span);
        const method = methodNames.get(resolved.method);
        if (!method) fail('E_CLASS_STATIC_METHOD', 'Static method lowering metadata is missing.', expr.span);
        return `${method}()`;
      }
      case 'consoleLog': {
        if (expr.args.length > 1) {
          const first = expr.args[0]!;
          if (first.kind !== 'literal')
            fail('E_CONSOLE_FORMAT', 'Multi-argument class-lane console.log requires a literal first argument to exclude Node format substitution.', expr.span);
          if (typeof first.value === 'string' && first.value.includes('%'))
            fail('E_CONSOLE_FORMAT', 'Node console format substitution is outside the class-lane host contract.', expr.span);
        }
        return `JsConsole.Log(${expr.args.map(emitExpr).join(', ')})`;
      }
    }
  }

  const lines: string[] = [
    '// Generated by j2cs-compiler LANGUAGE_CLASSES_SUPER lane.',
    '// See compilation.json for canonical class-rule hashes and proofs.',
    'using J2cs.Runtime;',
    '',
    'internal static class Program',
    '{',
  ];
  const line = (depth: number, value: string) => lines.push('    '.repeat(depth) + value);
  for (const { name } of classes.values()) line(1, `private static JsClass ${name} = null!;`);

  line(1, 'private static void Main()');
  line(1, '{');
  for (const item of program.items) {
    if (item.kind === 'class') {
      const target = classes.get(item.bindingName)!;
      if (item.baseName) line(2, `${target.name} = JsClass.CreateDerived(${quote(item.displayName)}, ${classes.get(item.baseName)!.name});`);
      else line(2, `${target.name} = JsClass.Create(${quote(item.displayName)});`);
      const fields = item.elements.filter(e => e.kind === 'staticField');
      if (fields.length) {
        line(2, `_ = JsClass.Initialize(${target.name}, () =>`);
        line(2, '{');
        for (const field of fields)
          line(3, `_ = JsClass.SetStatic(${target.name}, ${quote(field.name)}, ${emitExpr(field.initializer)});`);
        line(2, '});');
      }
      continue;
    }
    if (item.kind === 'console') line(2, `_ = JsConsole.Log(${item.args.map(emitExpr).join(', ')});`);
    else if (item.kind === 'staticAssign') {
      plan.resolveField(item.className, item.property, item.span);
      line(2, `_ = JsClass.SetStatic(${classRef(item.className, item.span)}, ${quote(item.property)}, ${emitExpr(item.value)});`);
    } else line(2, `_ = ${emitExpr(item.call)};`);
  }
  line(1, '}');

  for (const { parsed } of classes.values()) {
    for (const element of parsed.elements) {
      if (element.kind !== 'staticMethod') continue;
      const method = methodNames.get(element)!;
      line(0, '');
      line(1, `private static JsValue ${method}()`);
      line(1, '{');
      if (!element.result) fail('E_CLASS_DEPENDENCY', 'Dynamic static method body was not proven for lowering.', element.span);
      line(2, `return ${emitExpr(element.result)};`);
      line(1, '}');
    }
  }
  lines.push('}', '');

  const ir: CsProgram = { body: [], functions: [] };
  return {
    source: lines.join('\n'),
    ir,
    trace: plan.traces,
    structuralContracts: [
      'class.constructor-object.static-data-v1',
      'class.static-eager-initialization-v1',
      'class.instance-construction.fail-closed-until-dependent-lanes-merge',
    ],
  };
}
